name: Release workflow

on:
  push:
    branches:
      - 444-nathan
  workflow_dispatch:
    inputs:
      tag_name:
        description: "Version to produce"
        required: true
      draft:
        description: "Draft"
        required: true
        type: boolean
        default: true
      prerelease:
        description: "Pre-release"
        required: true
        type: boolean
        default: false
      generate_release_notes:
        description: "Generate release notes"
        required: true
        type: boolean
        default: true

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update Manifest
        run: |
          # Retrieve the latest tag name
          TAG_NAME=${{ github.event.inputs.tag_name }}
          
          # Update the version field in the manifest.json file
          sed -i "s/\"version\": \".*\",/\"version\": \"$TAG_NAME\",/" manifest.json
      - uses: EndBug/add-and-commit@v9
        with:
          message: 'Update version in manifest.json'
          commit: --no-verify
          committer_name: GitHub Actions
          committer_email: actions@github.com

  build-release:
    uses: ./.github/workflows/build.yml
    with:
      tag_name: ${{ github.event.inputs.tag_name }}
      draft: ${{ github.event.inputs.draft }}
      prerelease: ${{ github.event.inputs.prerelease }}
      generate_release_notes: ${{ github.event.inputs.generate_release_notes }}
